export const actionTypes = {
	START_LOGIN_USER: 'START_LOGIN_USER',
	LOGOUT_USER: 'LOGOUT_USER',
	START_GET_USER: 'START_GET_USER',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
	GET_USER_ERROR: 'GET_USER_ERROR',
};
