export const actionTypes = {
	START_FETCH_AUTHORS: 'START_FETCH_AUTHORS',
	FETCH_AUTHORS_SUCCESS: 'FETCH_AUTHORS_SUCCESS',
	FETCH_AUTHORS_ERROR: 'FETCH_AUTHORS_ERROR',
	ADD_AUTHOR: 'ADD_AUTHOR',
	SHOW_ERROR: 'SHOW_ERROR',
};
