export const actionTypes = {
	FETCH_COURSES_START: 'FETCH_COURSES_START',
	FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
	FETCH_COURSES_ERROR: 'FETCH_COURSES_ERROR',
	ADD_COURSE: 'ADD_COURSE',
	UPDATE_COURSE: 'UPDATE_COURSE',
	DELETE_COURSE: 'DELETE_COURSE',
	SHOW_ERROR: 'SHOW_ERROR',
};
